import "dotenv/config";
import { ImapFlow } from "imapflow";
import { closeDatabasePool, query } from "../config/database.js";
import {
  insertInboundEmail,
  insertInboundEmailAttachments,
  listActiveMailboxes,
} from "../repositories/inboundEmailRepository.js";
import { parseMessageSource } from "../services/inboundEmail/messageParser.js";
import { sanitizeEmailHtml } from "../services/inboundEmail/htmlSanitizer.js";
import { mailboxPassword } from "../services/inboundEmail/mailboxCredentials.js";
import {
  detectEscalation,
} from "../services/inboundEmail/escalationDetector.js";
import {
  extractWoNumbers,
  isAutoGenerated,
  isNoReplySender,
  toFullText,
  toPreview,
} from "../services/inboundEmail/emailMatcher.js";

/**
 * Fetch ONLY the mail needed to verify the quotations that are still open.
 *
 * The ingest reads from a watermark stamped when each mailbox was registered and never
 * moves it backwards, so mail that arrived before then is not held — which is why a
 * quotation raised in July shows no payment however clearly the customer confirmed one.
 *
 * The obvious fix is to drag the watermark back, and it is the wrong one: three weeks
 * across five mailboxes is a couple of thousand messages with their attachments, on a box
 * that ran out of disk this week, to answer a question about forty-nine quotations.
 *
 * So this asks the mail server the narrow question instead. For every open quotation it
 * searches that mailbox for its work order and for its customer's address, and fetches only
 * what comes back. A few hundred messages rather than a few thousand, and the ones that are
 * actually about a quotation.
 *
 * SAFE TO RE-RUN. The watermark is not touched, so the normal ingest is unaffected, and
 * storing is guarded by the same message_id conflict — a message already held is a no-op.
 *
 * ONE MAILBOX AT A TIME, if you name one. Searching is the slow half and it is slow per
 * mailbox, so a run that has already done four of them should not have to do those four
 * again to reach the fifth — and the fifth, the one registered most recently, is the one
 * whose history is missing. Each mailbox also gets a search budget, so one enormous INBOX
 * can no longer hold up every mailbox behind it.
 *
 *   node dist/scripts/fetchQuotationVerificationMail.js            # every mailbox
 *   node dist/scripts/fetchQuotationVerificationMail.js trade      # only that one
 */

/** Stop a runaway search from pulling half a mailbox. Per mailbox, per run. */
const MAX_PER_MAILBOX = Number(process.env.VERIFY_FETCH_MAX ?? 400) || 400;

/**
 * How long the searching may run for ONE mailbox before it settles for what it has.
 *
 * A TEXT search asks the server to read the body of every message in the folder, and there
 * are two searches per open quotation — sixty-odd quotations is over a hundred full passes
 * of an INBOX. On a mailbox that has been busy for years that is not slow, it is unbounded,
 * and because nothing prints until every search is done it reads as a hung script.
 *
 * Worse, it is unbounded in the wrong place: a run that never reaches the fifth mailbox has
 * done nothing at all for the fifth mailbox, and the mailbox registered last is exactly the
 * one whose history is missing. A budget turns "stuck on mailbox three" into "mailbox three
 * got five minutes and the rest still got their turn".
 *
 * What it gives up is stated out loud when it happens — a quiet cut here would read as full
 * coverage while being anything but.
 */
const SEARCH_BUDGET_MS = (Number(process.env.VERIFY_SEARCH_MINUTES ?? 5) || 5) * 60_000;

/** A progress line this often, so a long search cannot be mistaken for a dead one. */
const PROGRESS_EVERY = 10;

/**
 * One mailbox, named on the command line.
 *
 * Without it every registered mailbox is done in turn, which is right for a first run and
 * wrong for every run after: when four mailboxes are already done and the fifth is the one
 * that matters, working through the four again to reach it costs the whole of their search
 * time for nothing. Region code, address, or just the local part — `trade`, `TRADE` and
 * `trade@renderways.in` all name the same mailbox.
 *
 *   node dist/scripts/fetchQuotationVerificationMail.js trade
 */
function namesMailbox(
  mailbox: { email: string; regionCode: string },
  filter: string,
): boolean {
  if (!filter) return true;
  const email = mailbox.email.trim().toLowerCase();
  const localPart = email.split("@")[0] ?? "";
  return (
    email === filter || localPart === filter || mailbox.regionCode.trim().toLowerCase() === filter
  );
}

interface OpenQuotation {
  quotationNo: string;
  orderNumber: string;
  customerEmail: string;
  since: Date;
}

async function listOpenQuotations(): Promise<OpenQuotation[]> {
  const result = await query<{
    quotation_no: string;
    order_number: string;
    customer_email: string;
    since: string;
  }>(
    `SELECT quotation_no,
            COALESCE(order_number, '') AS order_number,
            LOWER(TRIM(COALESCE(NULLIF(sent_to, ''), customer_email, ''))) AS customer_email,
            COALESCE(sent_at, quotation_date::timestamptz)::TEXT AS since
       FROM quotations
      WHERE payment_status = 'PENDING'
      ORDER BY quotation_date`,
  );
  return result.rows
    .map((r) => ({
      quotationNo: r.quotation_no,
      orderNumber: r.order_number.trim(),
      customerEmail: r.customer_email.trim(),
      since: new Date(r.since),
    }))
    .filter((q) => q.orderNumber || q.customerEmail);
}

/**
 * Store one message, matching it the same way the ingest does.
 *
 * Matching matters as much as storing: a message saved without its work order is invisible
 * to the watcher, which finds replies BY work order. Kept deliberately close to the ingest's
 * own rules so a message fetched here is indistinguishable from one the sweep brought in.
 */
async function storeMessage(input: {
  mailboxEmail: string;
  regionCode: string;
  uid: number | null;
  envelope: { date?: Date; subject?: string; messageId?: string; from?: { address?: string; name?: string }[] } | undefined;
  source: Buffer;
  /**
   * The work order whose search turned this message up.
   *
   * Preferred over the first WO the text happens to contain, because that is often not the
   * one that matters: a forwarded HP thread lists a dozen work orders and the first is
   * whichever came up in conversation. The watcher looks replies up BY work order, so a
   * message filed under a neighbour's WO is invisible to the quotation it actually answers.
   */
  preferredWo: string;
}): Promise<boolean> {
  const parsed = await parseMessageSource(input.source);
  const envelope = input.envelope;
  const receivedAt = envelope?.date ?? new Date();

  const envelopeFrom = envelope?.from?.[0];
  const from = {
    email: (parsed.fromEmail || envelopeFrom?.address || "").trim().toLowerCase(),
    name: (parsed.fromName || envelopeFrom?.name || "").trim(),
  };
  const subject = (parsed.subject || envelope?.subject || "").trim();

  const plainSource = parsed.text.trim() ? parsed.text : parsed.html;
  const preview = toPreview(plainSource);
  const fullText = toFullText(plainSource);

  // The WO the watcher will look this up by. Same regex the ingest uses; no report lookup,
  // because a quotation's work order is worth recording whether or not a report row exists
  // for it today.
  const wos = extractWoNumbers(`${subject} ${preview}`);
  // The searched-for one when the message really does carry it; otherwise whatever it does
  // carry, which is what the ingest would have recorded anyway.
  const preferred = input.preferredWo.trim().toUpperCase();
  const matchedTicketId =
    preferred && wos.some((wo) => wo.toUpperCase() === preferred)
      ? preferred
      : (wos[0] ?? "");

  const autoFlag = isAutoGenerated(parsed.headers) || isNoReplySender(from.email);
  const escalation = detectEscalation({ subject, body: fullText, isAutoReply: autoFlag });

  const storedId = await insertInboundEmail({
    mailboxEmail: input.mailboxEmail,
    regionCode: input.regionCode,
    messageId: envelope?.messageId ?? `verify-${input.uid}@${input.mailboxEmail}`,
    imapUid: input.uid,
    fromEmail: from.email,
    fromName: from.name,
    subject,
    bodyPreview: preview,
    bodyText: fullText,
    bodyHtml: sanitizeEmailHtml(parsed.html),
    hasAttachments: parsed.attachments.some((a) => !a.isInline),
    receivedAt: receivedAt.toISOString(),
    matchedTicketId,
    matchedCaseId: "",
    matchMethod: matchedTicketId ? "WO_NUMBER" : "NONE",
    matchConfidence: matchedTicketId ? "HIGH" : "NONE",
    isAutoReply: autoFlag,
    escalationLevel: escalation.level,
    escalationReasons: escalation.reasons.join(" | "),
  });

  if (!storedId) return false;

  // The screenshot is the point of the exercise — without the bytes there is nothing to
  // read. A failure here still leaves the message itself readable.
  if (parsed.attachments.length > 0) {
    try {
      await insertInboundEmailAttachments(
        storedId,
        parsed.attachments.map((a) => ({
          contentId: a.contentId,
          filename: a.filename,
          mimeType: a.mimeType,
          sizeBytes: a.sizeBytes,
          isInline: a.isInline,
          content: a.content,
        })),
      );
    } catch (error) {
      console.error(`  attachments failed for uid ${String(input.uid)}:`, error);
    }
  }
  return true;
}

async function run(): Promise<void> {
  const quotations = await listOpenQuotations();
  if (quotations.length === 0) {
    console.log("No open quotations — nothing to verify.");
    return;
  }
  const earliest = quotations.reduce(
    (min, q) => (q.since < min ? q.since : min),
    quotations[0]!.since,
  );
  console.log(
    `Verifying ${quotations.length} open quotation(s), from ${earliest.toISOString().slice(0, 10)} onwards.\n` +
      `The ingest watermark is NOT touched — this only adds messages the search finds.\n`,
  );

  const host = process.env.MAIL_IMAP_HOST ?? "";
  const port = Number(process.env.MAIL_IMAP_PORT ?? 993);
  if (!host) {
    console.error("MAIL_IMAP_HOST is not set.");
    process.exitCode = 1;
    return;
  }

  const filter = (process.argv[2] ?? "").trim().toLowerCase();
  const all = await listActiveMailboxes();
  const mailboxes = all.filter((mailbox) => namesMailbox(mailbox, filter));
  if (filter && mailboxes.length === 0) {
    console.error(
      `No registered mailbox is called "${process.argv[2]}". The registered ones are:\n` +
        all.map((m) => `  ${m.regionCode}  ${m.email}`).join("\n"),
    );
    process.exitCode = 1;
    return;
  }
  if (filter) {
    console.log(`Only ${mailboxes.map((m) => m.email).join(", ")} — named on the command line.\n`);
  }
  let storedTotal = 0;

  for (const mailbox of mailboxes) {
    const pass = mailboxPassword(mailbox.email);
    if (!pass) {
      console.log(`${mailbox.email} — no password configured, skipped`);
      continue;
    }

    const client = new ImapFlow({
      host,
      port,
      secure: true,
      auth: { user: mailbox.email, pass },
      logger: false,
      tls: { rejectUnauthorized: false },
      socketTimeout: 15 * 60_000,
    });
    // An emitted 'error' with no listener is fatal to the process; this is a one-off
    // script but the same rule applies.
    client.on("error", (error: unknown) => {
      console.error(
        `  IMAP error on ${mailbox.email}:`,
        error instanceof Error ? error.message : error,
      );
    });

    let stored = 0;
    try {
      await client.connect();
      const lock = await client.getMailboxLock("INBOX");
      try {
        // Collected across every quotation first, so a message that answers two of them is
        // fetched once. The value is the work order that found it, so the message can be
        // filed under the one it was searched for rather than the first it mentions.
        const uids = new Map<number, string>();
        const deadline = Date.now() + SEARCH_BUDGET_MS;
        let asked = 0;
        let ranOutOfTime = false;

        for (const quotation of quotations) {
          if (Date.now() > deadline) {
            ranOutOfTime = true;
            break;
          }
          const searches: Array<{ criteria: Record<string, unknown>; wo: string }> = [];
          // The customer's own mail FIRST. It is a header search, so the server answers it
          // from what it already has indexed, where TEXT below makes it read every body in
          // the folder. When the budget runs out mid-mailbox, what has been collected by
          // then should be the cheap question asked of every quotation rather than the
          // expensive one asked of the first dozen — and a reply the customer sent is
          // precisely what the payment watch is waiting for.
          if (quotation.customerEmail) {
            searches.push({
              criteria: { since: quotation.since, from: quotation.customerEmail },
              wo: "",
            });
          }
          // The work order anywhere in the message — subject line, quoted body, forwarded
          // trail. TEXT is the broad one and the one that catches a forward.
          if (quotation.orderNumber) {
            searches.push({
              criteria: { since: quotation.since, text: quotation.orderNumber },
              wo: quotation.orderNumber,
            });
          }

          for (const { criteria, wo } of searches) {
            if (uids.size >= MAX_PER_MAILBOX) break;
            try {
              const found = await client.search(criteria, { uid: true });
              for (const uid of Array.isArray(found) ? found : []) {
                const value = Number(uid);
                if (Number.isInteger(value) && value > 0) {
                  // A work order names the job; a sender only names who wrote. So a WO claim
                  // fills in for a sender's blank, and nothing ever overwrites a WO already
                  // recorded — the first work order to find a message still keeps it, which
                  // is what stops a message being filed under a neighbour's job.
                  const claimed = uids.get(value);
                  if (claimed === undefined || (claimed === "" && wo !== "")) {
                    uids.set(value, wo);
                  }
                }
                if (uids.size >= MAX_PER_MAILBOX) break;
              }
            } catch (error) {
              console.error(
                `  search failed for ${quotation.quotationNo}:`,
                error instanceof Error ? error.message : error,
              );
            }
          }

          asked += 1;
          if (asked % PROGRESS_EVERY === 0) {
            console.log(
              `  ${mailbox.email} — asked about ${asked}/${quotations.length} quotation(s), ` +
                `${uids.size} message(s) found so far`,
            );
          }
        }
        if (ranOutOfTime) {
          // Said out loud. A cut this size passed over in silence would leave the run looking
          // like it covered everything, and the next person to wonder why a quotation is
          // still unanswered would have no reason to suspect it was never asked about.
          console.log(
            `  ${mailbox.email} — ${SEARCH_BUDGET_MS / 60_000} minute search budget used up after ` +
              `${asked}/${quotations.length} quotation(s). Fetching what was found; run it again ` +
              `for the rest.`,
          );
        }

        if (uids.size > 0) {
          const list = [...uids.keys()].sort((a, b) => a - b);
          console.log(`${mailbox.email} — ${list.length} message(s) matched, fetching…`);
          for await (const message of client.fetch(
            list,
            { uid: true, envelope: true, source: true },
            { uid: true },
          )) {
            try {
              const added = await storeMessage({
                mailboxEmail: mailbox.email,
                regionCode: mailbox.regionCode,
                uid: Number(message.uid) || null,
                envelope: message.envelope,
                source: message.source ?? Buffer.from([]),
                preferredWo: uids.get(Number(message.uid)) ?? "",
              });
              if (added) stored += 1;
            } catch (error) {
              console.error(
                `  could not store uid ${String(message.uid)}:`,
                error instanceof Error ? error.message : error,
              );
            }
          }
        }
      } finally {
        lock.release();
      }
    } catch (error) {
      console.error(
        `${mailbox.email} — failed:`,
        error instanceof Error ? error.message : error,
      );
    } finally {
      try {
        await client.logout();
      } catch {
        /* already closed */
      }
    }

    console.log(`${mailbox.email} — ${stored} new message(s) stored`);
    storedTotal += stored;
  }

  console.log(
    `\nDone. ${storedTotal} new message(s) stored.\n` +
      `The mail worker will read them on its next sweep (within 3 minutes) and settle\n` +
      `whichever quotations they answer.`,
  );
}

run()
  .catch((error: unknown) => {
    console.error(error);
    process.exitCode = 1;
  })
  .finally(() => {
    void closeDatabasePool();
  });
