import "dotenv/config";
import { ImapFlow } from "imapflow";
import { closeDatabasePool } from "../config/database.js";
import {
  insertInboundEmail,
  insertInboundEmailAttachments,
  listActiveMailboxes,
} from "../repositories/inboundEmailRepository.js";
import { parseMessageSource } from "../services/inboundEmail/messageParser.js";
import { sanitizeEmailHtml } from "../services/inboundEmail/htmlSanitizer.js";
import { mailboxPassword } from "../services/inboundEmail/mailboxCredentials.js";
import { detectEscalation } from "../services/inboundEmail/escalationDetector.js";
import { isCabMail } from "../services/inboundEmail/cabMailFilter.js";
import {
  extractWoNumbers,
  isAutoGenerated,
  isNoReplySender,
  toFullText,
  toPreview,
} from "../services/inboundEmail/emailMatcher.js";

/**
 * Bring the last two months of CAB mail in from the mailboxes.
 *
 * The CAB button filters what OpenCall holds, and OpenCall holds mail from the day each
 * mailbox was registered — not before. So pressing CAB shows three messages when there are
 * two months of them sitting on the server: the rest was never fetched, and no filter can
 * find mail that is not there.
 *
 * The obvious fix is to drag each mailbox's watermark back two months, and it is the wrong
 * one: that is thousands of messages across six mailboxes, with their attachments, to answer
 * a question about the handful that mention cabs. It would also make the normal ingest
 * re-read all of it on its next sweep.
 *
 * So this asks the mail server the narrow question instead. Per mailbox, one IMAP search for
 * "cab" in the subject and one for it in the sender, both bounded to the period — and only
 * what comes back is fetched.
 *
 * CAB MAIL ONLY. What the server returns is a substring match, so it hands back cable
 * quotes and cabinet keys along with the cabs. Those are dropped here rather than stored:
 * the whole point is to bring in cab mail and nothing else, and mail nobody asked for is not
 * made harmless by being filtered out again on the way to the screen.
 *
 * SAFE TO RE-RUN. No watermark is touched, so the normal ingest is unaffected, and storing
 * is guarded by the same message_id conflict the sweep uses — a message already held is a
 * no-op. Nothing is ever deleted.
 *
 *   node dist/scripts/fetchCabMail.js            # every mailbox, last 3 months
 *   node dist/scripts/fetchCabMail.js 6          # last 6 months instead
 */

/** How far back to reach. Three months is what was asked for; the argument overrides it. */
const DEFAULT_MONTHS = 3;

/**
 * What to ask the server for, per mailbox.
 *
 * Deliberately broader than the rule that decides what gets stored. IMAP SEARCH matches
 * substrings, so "big" brings back bigger, Bigham and every big delay along with the big
 * spare parts — and `isCabMail` throws those out before anything is written. Asking the
 * server for the exact phrase instead would be neater and would miss "BIG-SPARE", which
 * matches no phrase but is plainly one of these.
 */
const SEARCH_WORDS = ["cab", "big"] as const;

/** Per mailbox, per run. A guard against a search that matches half an inbox. */
const MAX_PER_MAILBOX = Number(process.env.CAB_FETCH_MAX ?? 500) || 500;

/**
 * Folders that hold mail somebody received, wherever they have since filed it.
 *
 * INBOX alone found six messages across six mailboxes in two months, which is not what two
 * months of cab mail looks like. Read mail gets moved — into a folder per subject, into an
 * archive, by a server rule — and a search of the inbox cannot see any of it.
 *
 * Sent is excluded because this table is received mail; storing outgoing mail here would
 * make it read as though the customer had written to us. Trash, Junk and Drafts are
 * excluded because they are, respectively, deleted, not ours, and never sent.
 */
function isReceivedFolder(path: string): boolean {
  const leaf = (path.split(/[./]/).pop() ?? "").trim().toLowerCase();
  return !/^(sent|trash|deleted|junk|spam|draft)/.test(leaf);
}

function monthsBefore(date: Date, months: number): Date {
  // Same care as the screen's date picker: `setMonth` alone turns "one month before 31
  // March" into 3 March, because February has no 31st and the surplus spills forward.
  const target = new Date(date.getFullYear(), date.getMonth() - months, 1);
  const lastDay = new Date(target.getFullYear(), target.getMonth() + 1, 0).getDate();
  target.setDate(Math.min(date.getDate(), lastDay));
  return target;
}

/**
 * Store one message the way the ingest would.
 *
 * Deliberately a copy of the sweep's own rules rather than a shared helper: this is a
 * one-off backfill, and refactoring the live ingest to serve it would put the mail that
 * arrives every three minutes at risk for the sake of a script that runs twice.
 */
async function storeMessage(input: {
  mailboxEmail: string;
  regionCode: string;
  uid: number | null;
  envelope:
    | { date?: Date; subject?: string; messageId?: string; from?: { address?: string; name?: string }[] }
    | undefined;
  source: Buffer;
}): Promise<{ stored: boolean; skippedNotCab: boolean }> {
  const parsed = await parseMessageSource(input.source);
  const envelope = input.envelope;
  const receivedAt = envelope?.date ?? new Date();

  const envelopeFrom = envelope?.from?.[0];
  const from = {
    email: (parsed.fromEmail || envelopeFrom?.address || "").trim().toLowerCase(),
    name: (parsed.fromName || envelopeFrom?.name || "").trim(),
  };
  const subject = (parsed.subject || envelope?.subject || "").trim();

  // IMAP SEARCH matches substrings, so "cable" and "cabinet" come back too. The word rule is
  // applied here, before anything is written — the same rule the CAB button uses, so what is
  // stored and what is shown cannot disagree.
  if (!isCabMail(from.email, subject)) return { stored: false, skippedNotCab: true };

  const plainSource = parsed.text.trim() ? parsed.text : parsed.html;
  const preview = toPreview(plainSource);
  const fullText = toFullText(plainSource);

  // The work order, when the message carries one. Recorded the same way the sweep records
  // it so a message fetched here is indistinguishable from one the sweep brought in.
  const wos = extractWoNumbers(`${subject} ${preview}`);
  const matchedTicketId = wos[0] ?? "";

  const autoFlag = isAutoGenerated(parsed.headers) || isNoReplySender(from.email);
  const escalation = detectEscalation({ subject, body: fullText, isAutoReply: autoFlag });

  const storedId = await insertInboundEmail({
    mailboxEmail: input.mailboxEmail,
    regionCode: input.regionCode,
    messageId: envelope?.messageId ?? `cab-${input.uid}@${input.mailboxEmail}`,
    imapUid: input.uid,
    fromEmail: from.email,
    fromName: from.name,
    subject,
    bodyPreview: preview,
    bodyText: fullText,
    bodyHtml: sanitizeEmailHtml(parsed.html),
    hasAttachments: parsed.attachments.some((a) => !a.isInline),
    receivedAt: receivedAt.toISOString(),
    matchedTicketId,
    matchedCaseId: "",
    matchMethod: matchedTicketId ? "WO_NUMBER" : "NONE",
    matchConfidence: matchedTicketId ? "HIGH" : "NONE",
    isAutoReply: autoFlag,
    escalationLevel: escalation.level,
    escalationReasons: escalation.reasons.join(" | "),
  });

  if (!storedId) return { stored: false, skippedNotCab: false };

  if (parsed.attachments.length > 0) {
    try {
      await insertInboundEmailAttachments(
        storedId,
        parsed.attachments.map((a) => ({
          contentId: a.contentId,
          filename: a.filename,
          mimeType: a.mimeType,
          sizeBytes: a.sizeBytes,
          isInline: a.isInline,
          content: a.content,
        })),
      );
    } catch (error) {
      console.error(`  attachments failed for uid ${String(input.uid)}:`, error);
    }
  }
  return { stored: true, skippedNotCab: false };
}

async function run(): Promise<void> {
  const monthsArg = Number(process.argv[2]);
  const months = Number.isFinite(monthsArg) && monthsArg > 0 ? Math.trunc(monthsArg) : DEFAULT_MONTHS;
  const since = monthsBefore(new Date(), months);

  const host = process.env.MAIL_IMAP_HOST ?? "";
  const port = Number(process.env.MAIL_IMAP_PORT ?? 993);
  if (!host) {
    console.error("MAIL_IMAP_HOST is not set on this service.");
    process.exitCode = 1;
    return;
  }

  console.log("=".repeat(74));
  console.log(`CAB MAIL BACKFILL — last ${months} month(s), from ${since.toISOString().slice(0, 10)}`);
  console.log("Only mail whose sender or subject carries cab, or big spare/part/product.");
  console.log("The ingest watermark is NOT touched, and nothing is ever deleted.");
  console.log("=".repeat(74));

  const mailboxes = await listActiveMailboxes();
  let storedTotal = 0;

  for (const mailbox of mailboxes) {
    const pass = mailboxPassword(mailbox.email);
    if (!pass) {
      console.log(`${mailbox.email} — no password on this service, skipped`);
      continue;
    }

    const client = new ImapFlow({
      host,
      port,
      secure: true,
      auth: { user: mailbox.email, pass },
      logger: false,
      tls: { rejectUnauthorized: false },
      socketTimeout: 15 * 60_000,
    });
    // An 'error' with no listener ends the process — the same rule as everywhere else an
    // ImapFlow client is built.
    client.on("error", (error: unknown) => {
      console.error(`  IMAP error on ${mailbox.email}:`, error instanceof Error ? error.message : error);
    });

    let stored = 0;
    let notCab = 0;
    try {
      await client.connect();

      // Every folder that holds received mail, not just INBOX. Read mail gets filed away,
      // and the first run of this searched only the inbox and found six messages in two
      // months across six mailboxes — which is not what two months of cab mail looks like.
      const folders = (await client.list())
        .map((box) => String(box.path ?? "").trim())
        .filter((path) => path && isReceivedFolder(path));
      console.log(`${mailbox.email} — ${folders.length} folder(s): ${folders.join(", ")}`);

      let matchedHere = 0;
      for (const folder of folders) {
        let lock;
        try {
          lock = await client.getMailboxLock(folder);
        } catch (error) {
          console.error(
            `  could not open ${folder}:`,
            error instanceof Error ? error.message : error,
          );
          continue;
        }
        try {
          // Each word asked of the subject and of the sender, deduplicated. Asking only
          // about the subject would miss a booking desk that writes nothing useful in it.
          const uids = new Set<number>();
          const searches = SEARCH_WORDS.flatMap((word) => [
            { since, subject: word },
            { since, from: word },
          ]);
          for (const criteria of searches) {
            try {
              const found = await client.search(criteria, { uid: true });
              for (const uid of Array.isArray(found) ? found : []) {
                const value = Number(uid);
                if (Number.isInteger(value) && value > 0) uids.add(value);
                if (uids.size >= MAX_PER_MAILBOX) break;
              }
            } catch (error) {
              console.error(
                `  search failed in ${folder}:`,
                error instanceof Error ? error.message : error,
              );
            }
          }
          if (uids.size === 0) continue;

          const list = [...uids].sort((a, b) => a - b);
          matchedHere += list.length;
          console.log(`  ${folder} — ${list.length} matched, fetching…`);
          for await (const message of client.fetch(
            list,
            { uid: true, envelope: true, source: true },
            { uid: true },
          )) {
            try {
              const result = await storeMessage({
                mailboxEmail: mailbox.email,
                regionCode: mailbox.regionCode,
                uid: Number(message.uid) || null,
                envelope: message.envelope,
                source: message.source ?? Buffer.from([]),
              });
              if (result.stored) stored += 1;
              if (result.skippedNotCab) notCab += 1;
            } catch (error) {
              console.error(
                `  could not store uid ${String(message.uid)}:`,
                error instanceof Error ? error.message : error,
              );
            }
          }
        } finally {
          lock.release();
        }
      }
      if (matchedHere === 0) console.log(`  nothing matched in any folder`);
    } catch (error) {
      console.error(`${mailbox.email} — failed:`, error instanceof Error ? error.message : error);
    } finally {
      try {
        await client.logout();
      } catch {
        /* already closed */
      }
    }

    console.log(
      `${mailbox.email} — ${stored} new CAB message(s) stored` +
        (notCab > 0 ? `, ${notCab} skipped (cable, bigger, big delay — not this desk)` : ""),
    );
    storedTotal += stored;
  }

  console.log(
    `\nDone. ${storedTotal} new CAB message(s) stored.\n` +
      `Open Customer Emails and press CAB — the last ${months} months are there now.`,
  );
}

run()
  .catch((error: unknown) => {
    console.error(error);
    process.exitCode = 1;
  })
  .finally(() => {
    void closeDatabasePool();
  });
