/**
 * Matching an inbound customer email to a call, and spotting messages that must never be
 * auto-answered. Pure functions — no DB, no IMAP — so the rules are unit-testable.
 */

export type MatchMethod = "WO_NUMBER" | "CUSTOMER_EMAIL" | "NONE";
export type MatchConfidence = "HIGH" | "LOW" | "NONE";

/**
 * WO / ticket numbers as they appear in this system: "WO-035073100". Tolerates a missing
 * hyphen and surrounding punctuation, which is how customers actually type them.
 */
const WO_PATTERN = /\bWO[-\s]?(\d{6,12})\b/gi;

/** Every distinct WO number mentioned, normalised to `WO-<digits>`, first mention first. */
export function extractWoNumbers(text: string): string[] {
  const found: string[] = [];
  const seen = new Set<string>();
  for (const match of String(text ?? "").matchAll(WO_PATTERN)) {
    const normalised = `WO-${match[1]}`;
    if (!seen.has(normalised)) {
      seen.add(normalised);
      found.push(normalised);
    }
  }
  return found;
}

/**
 * Headers that mark a message as machine-generated. Replying to one of these is exactly how
 * an auto-responder loop starts, so anything flagged here is barred from the reply path.
 */
export function isAutoGenerated(headers: Record<string, string | undefined>): boolean {
  const get = (name: string) => (headers[name.toLowerCase()] ?? "").toLowerCase();

  const autoSubmitted = get("auto-submitted");
  if (autoSubmitted && autoSubmitted !== "no") return true;

  if (get("x-autoreply")) return true;
  if (get("x-autorespond")) return true;
  if (["bulk", "auto_reply", "junk", "list"].includes(get("precedence"))) return true;
  if (get("x-auto-response-suppress")) return true;
  // A mailing-list post is not a customer asking about their call.
  if (get("list-id") || get("list-unsubscribe")) return true;

  return false;
}

/** A no-reply style sender should never be written back to. */
export function isNoReplySender(fromEmail: string): boolean {
  return /(^|[._-])(no[-._]?reply|do[-._]?not[-._]?reply|mailer[-._]?daemon|postmaster|bounce)/i.test(
    String(fromEmail ?? "").split("@")[0] ?? "",
  );
}

export interface MatchResult {
  ticketId: string;
  caseId: string;
  method: MatchMethod;
  confidence: MatchConfidence;
}

export const NO_MATCH: MatchResult = {
  ticketId: "",
  caseId: "",
  method: "NONE",
  confidence: "NONE",
};

/**
 * Decide the match from what the lookups found.
 *
 * A WO number quoted by the customer AND present in the report is the only HIGH-confidence
 * result — that is the one a reply may eventually be sent for. Recognising the sender's
 * address alone is LOW: one contact can have several calls, so the message may be about a
 * different one. A WO number that matches no report row is not a match at all.
 */
export function resolveMatch(input: {
  woInReport: { ticketId: string; caseId: string } | null;
  senderRow: { ticketId: string; caseId: string } | null;
}): MatchResult {
  if (input.woInReport) {
    return {
      ticketId: input.woInReport.ticketId,
      caseId: input.woInReport.caseId,
      method: "WO_NUMBER",
      confidence: "HIGH",
    };
  }
  if (input.senderRow) {
    return {
      ticketId: input.senderRow.ticketId,
      caseId: input.senderRow.caseId,
      method: "CUSTOMER_EMAIL",
      confidence: "LOW",
    };
  }
  return NO_MATCH;
}

/**
 * Pull the readable part out of a raw IMAP body.
 *
 * Real mail from HP/Flex arrives as multipart MIME with quoted-printable HTML, so the raw
 * part starts with boundary markers and `Content-Type:` headers. Taking it verbatim filled
 * the preview with `--_007_MAZP287...` and `<html><meta http-equiv=3D"...">` instead of
 * anything a coordinator could read. Prefer the text/plain section; fall back to stripping
 * the HTML.
 */
function extractReadableBody(raw: string): string {
  const text = String(raw ?? "").replace(/\r/g, "");

  // Split a multipart body on its boundary markers. The first boundary sits at the very
  // start of the part with no leading newline, and nested multipart/alternative adds more,
  // so anchor on start-of-line rather than requiring a preceding "\n".
  const parts = /^--[^\n]*$/m.test(text)
    ? text.split(/^--[^\n]*$/m).filter((p) => p.trim())
    : [text];

  const sections = parts.map((part) => {
    // A MIME part carries its own headers before a blank line. Only strip that block when
    // it really is headers — a plain message's first paragraph is also followed by a blank
    // line, and treating that as headers threw away what the customer actually wrote.
    const headerEnd = part.search(/\n\s*\n/);
    const candidate = headerEnd > 0 ? part.slice(0, headerEnd) : "";
    const isHeaderBlock = /^\s*content-(type|transfer-encoding)\s*:/im.test(candidate);
    const headers = isHeaderBlock ? candidate.toLowerCase() : "";
    const body = isHeaderBlock ? part.slice(headerEnd) : part;
    // Decode on the evidence, not just the header: nested multipart parts often carry the
    // encoding on an outer part, which left "5163= 318048" and "au= thorized" in the
    // preview. A soft line break or an =XX escape is proof enough.
    const looksEncoded =
      headers.includes("quoted-printable") || /=\n|=[0-9A-F]{2}/i.test(body);
    return {
      body: looksEncoded ? decodeQuotedPrintable(body) : body,
      isPlain: headers.includes("text/plain"),
      isHtml: headers.includes("text/html") || /<html|<body|<div|<p[ >]/i.test(body),
    };
  });

  const plain = sections.find((s) => s.isPlain && s.body.trim());
  if (plain) return plain.body;

  const html = sections.find((s) => s.isHtml && s.body.trim());
  if (html) return stripHtml(html.body);

  const any = sections.find((s) => s.body.trim());
  const body = any?.body ?? text;
  return /<[a-z][\s\S]*>/i.test(body) ? stripHtml(body) : body;
}

/** Quoted-printable: `=3D` escapes and `=` soft line breaks. */
function decodeQuotedPrintable(value: string): string {
  return value
    .replace(/=\n/g, "")
    .replace(/=([0-9A-Fa-f]{2})/g, (_, hex: string) =>
      String.fromCharCode(Number.parseInt(hex, 16)),
    );
}

function stripHtml(value: string): string {
  return value
    .replace(/<(script|style)[\s\S]*?<\/\1>/gi, " ")
    .replace(/<br\s*\/?>/gi, "\n")
    .replace(/<\/(p|div|tr|li|h[1-6])>/gi, "\n")
    .replace(/<[^>]+>/g, " ")
    .replace(/&nbsp;/gi, " ")
    .replace(/&amp;/gi, "&")
    .replace(/&lt;/gi, "<")
    .replace(/&gt;/gi, ">")
    .replace(/&quot;/gi, '"')
    .replace(/&#39;/g, "'");
}

/**
 * The whole message as readable text, with paragraph breaks kept — this is what the
 * reading pane shows. The quoted thread is NOT stripped here: when you open a mail you
 * want the history, unlike the one-line list preview.
 */
export function toFullText(body: string, limit = 50_000): string {
  return extractReadableBody(body)
    .split("\n")
    .map((line) => line.replace(/[ \t]+/g, " ").trimEnd())
    .join("\n")
    .replace(/\n{3,}/g, "\n\n")
    .trim()
    .slice(0, limit);
}

/** Collapse a mail body to a short, single-spaced triage preview. */
export function toPreview(body: string, limit = 500): string {
  return extractReadableBody(body)
    // Drop quoted history so the preview shows what THEY wrote, not the thread.
    .split(/^\s*(?:On .+ wrote:|-{2,}\s*Original Message|_{5,})/m)[0]!
    .split("\n")
    .map((line) => line.trim())
    .filter((line) => line && !line.startsWith(">"))
    .join(" ")
    .replace(/\s+/g, " ")
    .trim()
    .slice(0, limit);
}
