import { describe, expect, it } from "vitest";
import {
  extractWoNumbers,
  isAutoGenerated,
  isNoReplySender,
  resolveMatch,
  toFullText,
  toPreview,
} from "./emailMatcher.js";

const b64 = (value: string): string => Buffer.from(value, "utf8").toString("base64");

// These rules decide which customer message gets attached to which call, and which
// messages must never be written back to. Stage 1 only displays the result, but the same
// rules gate the reply path later, so they are pinned here.

describe("extractWoNumbers", () => {
  it("finds a WO number in a subject line", () => {
    expect(extractWoNumbers("Re: Service update WO-035073100")).toEqual(["WO-035073100"]);
  });

  it("tolerates how customers actually type it", () => {
    expect(extractWoNumbers("wo 035073100 pending")).toEqual(["WO-035073100"]);
    expect(extractWoNumbers("WO035073100")).toEqual(["WO-035073100"]);
    expect(extractWoNumbers("(WO-035073100)")).toEqual(["WO-035073100"]);
  });

  it("returns every distinct number, first mention first, without duplicates", () => {
    expect(
      extractWoNumbers("WO-035073100 and WO-035031434, again WO-035073100"),
    ).toEqual(["WO-035073100", "WO-035031434"]);
  });

  it("ignores things that only look like a WO number", () => {
    expect(extractWoNumbers("no ticket here")).toEqual([]);
    expect(extractWoNumbers("WO-123")).toEqual([]); // too short to be one of ours
    expect(extractWoNumbers("")).toEqual([]);
  });
});

describe("isAutoGenerated", () => {
  it("catches the standard auto-responder headers", () => {
    expect(isAutoGenerated({ "auto-submitted": "auto-replied" })).toBe(true);
    expect(isAutoGenerated({ "x-autoreply": "yes" })).toBe(true);
    expect(isAutoGenerated({ "x-autorespond": "1" })).toBe(true);
    expect(isAutoGenerated({ precedence: "bulk" })).toBe(true);
    expect(isAutoGenerated({ "x-auto-response-suppress": "All" })).toBe(true);
  });

  it("treats a mailing-list post as machine mail, not a customer", () => {
    expect(isAutoGenerated({ "list-id": "<news.example.com>" })).toBe(true);
    expect(isAutoGenerated({ "list-unsubscribe": "<mailto:x@y>" })).toBe(true);
  });

  it("lets a genuine human message through", () => {
    expect(isAutoGenerated({})).toBe(false);
    expect(isAutoGenerated({ "auto-submitted": "no" })).toBe(false);
    expect(isAutoGenerated({ precedence: "normal" })).toBe(false);
  });
});

describe("isNoReplySender", () => {
  it("spots addresses that must never be written back to", () => {
    expect(isNoReplySender("no-reply@hp.com")).toBe(true);
    expect(isNoReplySender("noreply@hp.com")).toBe(true);
    expect(isNoReplySender("do-not-reply@vendor.in")).toBe(true);
    expect(isNoReplySender("MAILER-DAEMON@host.net")).toBe(true);
    expect(isNoReplySender("postmaster@host.net")).toBe(true);
  });

  it("leaves a normal customer address alone", () => {
    expect(isNoReplySender("ravi.kumar@acme.test")).toBe(false);
    expect(isNoReplySender("info@bitbotit.com")).toBe(false);
  });
});

describe("resolveMatch", () => {
  it("treats a quoted WO number that exists in the report as high confidence", () => {
    const m = resolveMatch({
      woInReport: { ticketId: "WO-035073100", caseId: "5123" },
      senderRow: null,
    });
    expect(m).toEqual({
      ticketId: "WO-035073100",
      caseId: "5123",
      method: "WO_NUMBER",
      confidence: "HIGH",
    });
  });

  it("prefers the WO number over the sender when both are known", () => {
    const m = resolveMatch({
      woInReport: { ticketId: "WO-1", caseId: "a" },
      senderRow: { ticketId: "WO-2", caseId: "b" },
    });
    expect(m.ticketId).toBe("WO-1");
    expect(m.method).toBe("WO_NUMBER");
  });

  it("only gives the sender-address match LOW confidence", () => {
    // One contact can have several calls, so this must never be auto-answered.
    const m = resolveMatch({
      woInReport: null,
      senderRow: { ticketId: "WO-9", caseId: "c" },
    });
    expect(m.method).toBe("CUSTOMER_EMAIL");
    expect(m.confidence).toBe("LOW");
  });

  it("is no match at all when nothing is recognised", () => {
    const m = resolveMatch({ woInReport: null, senderRow: null });
    expect(m).toEqual({ ticketId: "", caseId: "", method: "NONE", confidence: "NONE" });
  });
});

describe("toPreview", () => {
  it("collapses the message to a single readable line", () => {
    expect(toPreview("Hello\n\n  there\r\n  team  ")).toBe("Hello there team");
  });

  it("drops the quoted thread so the preview is what THEY wrote", () => {
    const body = "Any update please?\n\nOn Mon, 4 Aug 2026, Support wrote:\n> earlier reply";
    expect(toPreview(body)).toBe("Any update please?");
  });

  it("drops quoted lines and the Original Message separator", () => {
    expect(toPreview("My question\n> your old text")).toBe("My question");
    expect(toPreview("Question\n----- Original Message -----\nold")).toBe("Question");
  });

  it("truncates to the limit", () => {
    expect(toPreview("x".repeat(900)).length).toBe(500);
    expect(toPreview("x".repeat(900), 50).length).toBe(50);
  });


  // Real HP/Flex mail arrives as multipart MIME with quoted-printable HTML, which used to
  // fill the preview with boundary markers and tags instead of anything readable.
  it("pulls the text/plain section out of a multipart MIME body", () => {
    const raw = [
      "--_007_MAZP287MB0586_",
      "Content-Type: text/plain; charset=us-ascii",
      "",
      "Please share the status of my call.",
      "--_007_MAZP287MB0586_",
      "Content-Type: text/html; charset=us-ascii",
      "",
      "<html><body><p>Please share the status of my call.</p></body></html>",
      "--_007_MAZP287MB0586_--",
    ].join("\n");
    expect(toPreview(raw)).toBe("Please share the status of my call.");
  });

  it("decodes quoted-printable and strips HTML when there is no plain part", () => {
    const raw = [
      "Content-Type: text/html; charset=us-ascii",
      "Content-Transfer-Encoding: quoted-printable",
      "",
      "<html><body><p>Call =3D closed<br>Thanks &amp; regards</p></body></html>",
    ].join("\n");
    expect(toPreview(raw)).toBe("Call = closed Thanks & regards");
  });

  it("never leaks MIME boundaries or tags into the preview", () => {
    const raw =
      "--_007_ABC_\nContent-Type: text/html\n\n<div>Hi <b>team</b></div>";
    const out = toPreview(raw);
    expect(out).not.toMatch(/--_007|Content-Type|<[a-z]/i);
    expect(out).toBe("Hi team");
  });

  it("survives an empty body", () => {
    expect(toPreview("")).toBe("");
  });
});

// Production showed a whole reading pane of "UmVtaW5kZXIuDQoNCg0K..." — HP's Outlook sends
// base64 with no per-part headers, and the quoted-printable path could not see it. Base64
// padding ("=") also looks like a QP escape, so the order these are tried in is load-bearing.
describe("base64 bodies", () => {
  it("decodes a bare base64 body that carries no MIME headers", () => {
    const raw = b64("Reminder.\r\n\r\nThanks and Regards\r\nBhupesh Sharma");
    expect(toPreview(raw)).toBe("Reminder. Thanks and Regards Bhupesh Sharma");
  });

  it("keeps the paragraph breaks of a decoded body in the reading pane", () => {
    const raw = b64("Reminder.\r\n\r\nThanks and Regards\r\nBhupesh Sharma");
    expect(toFullText(raw)).toBe("Reminder.\n\nThanks and Regards\nBhupesh Sharma");
  });

  it("decodes a part declared as base64", () => {
    const raw = [
      "Content-Type: text/plain; charset=utf-8",
      "Content-Transfer-Encoding: base64",
      "",
      b64("Please share the status of my call."),
    ].join("\n");
    expect(toPreview(raw)).toBe("Please share the status of my call.");
  });

  it("decodes base64 HTML and then strips the tags", () => {
    const raw = [
      "Content-Type: text/html; charset=utf-8",
      "Content-Transfer-Encoding: base64",
      "",
      b64("<html><body><p>Call closed<br>Thanks &amp; regards</p></body></html>"),
    ].join("\n");
    expect(toPreview(raw)).toBe("Call closed Thanks & regards");
  });

  it("handles the wrapped lines a mail server inserts", () => {
    const message = "Please update the status of this work order at the earliest.";
    const wrapped = b64(message).replace(/(.{20})/g, "$1\n");
    expect(toPreview(wrapped)).toBe(message);
  });

  // The failure that matters: mistaking a customer's own words for base64 would replace
  // their message with garbage. Prose must always survive untouched.
  it("never treats ordinary prose as base64", () => {
    expect(toPreview("Any update on this please")).toBe("Any update on this please");
    expect(toPreview("Reminder")).toBe("Reminder");
    expect(toPreview("WO035104670 pending")).toBe("WO035104670 pending");
  });

  // Run-together text satisfies the base64 alphabet by accident. Decoding it would hand
  // the reader binary noise in place of a real sentence, so the decode must be rejected.
  it("keeps run-together prose that only looks like base64", () => {
    const runTogether = "WO035104670PendingUpdateRequiredPleaseCheck";
    expect(toPreview(runTogether)).toBe(runTogether);
  });

  it("leaves quoted-printable alone", () => {
    const raw = [
      "Content-Type: text/plain",
      "Content-Transfer-Encoding: quoted-printable",
      "",
      "Call =3D closed",
    ].join("\n");
    expect(toPreview(raw)).toBe("Call = closed");
  });
});
