import { ImapFlow } from "imapflow";
import {
  ensureMailbox,
  findRowByCustomerEmail,
  findRowByTicketId,
  insertInboundEmail,
  insertInboundEmailAttachments,
  listActiveMailboxes,
  listStoredImapUids,
  markMailboxPolled,
  type RegionMailbox,
} from "../../repositories/inboundEmailRepository.js";
import { sanitizeEmailHtml } from "./htmlSanitizer.js";
import { parseMessageSource } from "./messageParser.js";
import {
  extractWoNumbers,
  isAutoGenerated,
  isNoReplySender,
  resolveMatch,
  toPreview,
  toFullText,
  NO_MATCH,
} from "./emailMatcher.js";
import { detectEscalation } from "./escalationDetector.js";
import { mailboxPassword } from "./mailboxCredentials.js";

/**
 * Customer email ingest — Stage 1: READ ONLY.
 *
 * Polls each registered region mailbox over IMAP, stores messages received AT OR AFTER that
 * mailbox's watermark, and records the best match to an open call.
 *
 * NOTHING IS EVER SENT. There is no SMTP code in this file on purpose: replies are a later
 * stage, switched on only once the matching has been watched in the UI.
 *
 * THE WATERMARK MATTERS. The live mailboxes hold years of history (3.5k-6.5k messages).
 * The IMAP SEARCH is bounded by `ingest_from`, stamped when the mailbox was registered, so
 * the back catalogue is never read and — when replies do arrive — no historical customer can
 * be answered years late.
 */

/**
 * How many messages one sweep will read from one mailbox.
 *
 * A backlog is drained in bites rather than swallowed. Left unbounded, a mailbox a few days
 * behind hands the sweep several hundred whole messages at once — too much to hold and too
 * long to read — and the sweep dies with nothing to show for it, restarts, and meets the
 * same backlog. Bounded, a backlog takes several sweeps to clear and every sweep leaves the
 * mailbox strictly further ahead than it found it.
 */
const MAX_MESSAGES_PER_SWEEP = (() => {
  const raw = Number(process.env.MAIL_MAX_PER_SWEEP);
  return Number.isFinite(raw) && raw > 0 ? Math.floor(raw) : 20;
})();

/**
 * Ceiling on the bytes one sweep holds from one mailbox.
 *
 * The count above bounds the batch by message; this bounds it by size, which is the one
 * that matters for a worker with a memory limit. Twenty messages is a small batch until one
 * of them carries a 20 MB report, and the worker has already been OOM-killed once for
 * assuming otherwise. Reaching this stops the read early — the messages not read were never
 * stored, so they are still pending and the next sweep takes them.
 */
const MAX_SWEEP_BYTES = (() => {
  const raw = Number(process.env.MAIL_MAX_SWEEP_MB);
  const mb = Number.isFinite(raw) && raw > 0 ? raw : 48;
  return Math.floor(mb * 1024 * 1024);
})();

/**
 * Idle ceiling for the IMAP socket. imapflow's own default is five minutes, which the old
 * read-and-store-together sweep used to reach; the two phases below are what keep a sweep
 * clear of it, and this is only the margin around them.
 */
const SOCKET_TIMEOUT_MS = 15 * 60_000;

/**
 * One message as it comes off the wire, before anything is made of it.
 *
 * Deliberately raw: holding the parsed form would mean parsing with the connection still
 * open, which is the coupling the two phases exist to break.
 */
interface CollectedMessage {
  uid: number | null;
  envelope: { date?: Date; subject?: string; messageId?: string; from?: { address?: string; name?: string }[] } | undefined;
  source: Buffer;
}

/**
 * The UIDs a sweep still owes work for: everything the server offered, minus what is
 * already stored, oldest first.
 *
 * Oldest first is the point. The batch is taken off the front of this list, so a mailbox
 * that has fallen behind catches up in arrival order and the reading pane fills in from
 * where it stopped rather than from both ends at once.
 */
export function pendingUids(
  offered: Array<number | string>,
  known: Set<number>,
): number[] {
  const seen = new Set<number>();
  const pending: number[] = [];
  for (const raw of offered) {
    // IMAP UIDs start at 1, so the `> 0` test is what rejects a blank entry — Number("")
    // is 0, which is finite, and a fetch for UID 0 asks the server for nothing.
    const uid = Number(raw);
    if (!Number.isInteger(uid) || uid <= 0 || known.has(uid) || seen.has(uid)) continue;
    seen.add(uid);
    pending.push(uid);
  }
  return pending.sort((a, b) => a - b);
}

export interface MailboxConfig {
  regionCode: string;
  email: string;
}

/** Mailboxes declared in the environment. Chennai/Hosur appear once their keys are set. */
export function mailboxesFromEnv(): MailboxConfig[] {
  const map: Array<[string, string | undefined]> = [
    ["CHENNAI", process.env.MAIL_CHENNAI],
    ["SALEM", process.env.MAIL_SALEM],
    ["HOSUR", process.env.MAIL_HOSUR],
    ["VELLORE", process.env.MAIL_VELLORE],
    ["KANCHIPURAM", process.env.MAIL_KANCHIPURAM],
  ];
  return map
    .filter((entry): entry is [string, string] => Boolean(entry[1]?.trim()))
    .map(([regionCode, email]) => ({ regionCode, email: email.trim() }));
}

/** Register every configured mailbox, stamping each one's watermark on first sight. */
export async function registerConfiguredMailboxes(): Promise<RegionMailbox[]> {
  const registered: RegionMailbox[] = [];
  for (const config of mailboxesFromEnv()) {
    registered.push(await ensureMailbox(config));
  }
  return registered;
}

function firstAddress(
  value: { address?: string; name?: string }[] | undefined,
): { email: string; name: string } {
  const first = value?.[0];
  return {
    email: (first?.address ?? "").trim().toLowerCase(),
    name: (first?.name ?? "").trim(),
  };
}

export interface PollResult {
  mailbox: string;
  fetched: number;
  /** Of those, the ones not yet held — the backlog still to drain, batch cap aside. */
  pending: number;
  stored: number;
  matched: number;
  error: string;
}

/**
 * Poll one mailbox. Never throws: a mailbox that is down must not stop the others, and the
 * failure is recorded on the mailbox row for the UI.
 */
export async function pollMailbox(mailbox: RegionMailbox): Promise<PollResult> {
  const result: PollResult = {
    mailbox: mailbox.email,
    fetched: 0,
    pending: 0,
    stored: 0,
    matched: 0,
    error: "",
  };

  const host = process.env.MAIL_IMAP_HOST ?? "";
  const port = Number(process.env.MAIL_IMAP_PORT ?? 993);
  // This mailbox's own password when it has one — hosur's differs from the rest.
  const pass = mailboxPassword(mailbox.email);
  if (!host || !pass) {
    result.error = "MAIL_IMAP_HOST / MAIL_PASSWORD not configured";
    await markMailboxPolled(mailbox.email, result.error);
    return result;
  }

  const client = new ImapFlow({
    host,
    port,
    secure: true,
    auth: { user: mailbox.email, pass },
    logger: false,
    // The mailboxes are on shared hosting with a self-signed chain on some hostnames.
    tls: { rejectUnauthorized: false },
    socketTimeout: SOCKET_TIMEOUT_MS,
  });

  // ImapFlow is an EventEmitter, and a socket that times out or drops emits 'error'
  // ASYNCHRONOUSLY — off the await chain below, where the try/catch cannot see it. Node
  // treats an 'error' with no listener as fatal and takes the process down with it, so a
  // single slow batch used to kill the worker outright, and the restart met the same
  // backlog and died the same way. Listening demotes it to a failure of this one mailbox.
  let socketError = "";
  client.on("error", (error: unknown) => {
    socketError = error instanceof Error ? error.message : String(error);
    console.error(`[mailWorker] IMAP error on ${mailbox.email}: ${socketError}`);
  });

  // ---- Phase 1: READ. The connection is open only for this. ----------------------
  //
  // Nothing that touches the database happens while the socket is live. imapflow's idle
  // ceiling counts silence on the socket, and the per-message work below — parsing, two
  // report lookups, an insert, attachment bytes — is slow enough that a full batch of it
  // used to leave the connection silent for minutes and the server hung up mid-sweep.
  // Reading is pure network and finishes quickly; the slow half runs once it is over.
  const since = new Date(mailbox.ingestFrom);
  const collected: CollectedMessage[] = [];
  let readError = "";

  // Read before connecting. It is one query rather than one per message, but it is still
  // database work, and the whole point of the split below is that none of that happens
  // with the socket open and counting silence against us.
  const known = await listStoredImapUids(mailbox.email);

  try {
    await client.connect();
    const lock = await client.getMailboxLock("INBOX");
    try {
      // THE GUARD: only mail at or after the watermark is even asked for.
      const uids = await client.search({ since }, { uid: true });
      const list = Array.isArray(uids) ? uids : [];
      result.fetched = list.length;

      // The SEARCH re-offers the entire range on every sweep, so subtract what is already
      // held before choosing a batch. Without this the cap below would re-read the same
      // oldest messages for ever and never reach today's mail.
      const pending = pendingUids(list, known);
      result.pending = pending.length;

      // Oldest first so the backlog drains in the order it arrived.
      const batch = pending.slice(0, MAX_MESSAGES_PER_SWEEP);

      if (batch.length > 0) {
        // The whole message, not just its text part: the reading pane shows the sender's
        // own HTML and their inline pictures, and both live in parts a "text" fetch skips.
        // Holding those whole messages is what the byte budget is for — twenty of them is
        // a modest batch by count and an unbounded one by size, and the worker has been
        // OOM-killed by exactly that before.
        let budget = MAX_SWEEP_BYTES;
        for await (const message of client.fetch(
          batch,
          { uid: true, envelope: true, source: true },
          { uid: true },
        )) {
          const source = message.source ?? Buffer.from([]);
          collected.push({
            uid: Number(message.uid) || null,
            envelope: message.envelope,
            source,
          });
          budget -= source.byteLength;
          // Stopping here costs nothing: what was not read was never stored, so it is
          // still pending and the next sweep takes it.
          if (budget <= 0) break;
        }
      }
    } finally {
      lock.release();
    }
  } catch (error) {
    const thrown = error instanceof Error ? error.message : String(error);
    // A dropped socket surfaces here as a generic abort; the emitted event carried the
    // real reason, so prefer it when there is one.
    readError = socketError || thrown;
  } finally {
    try {
      await client.logout();
    } catch {
      /* already closed */
    }
  }

  // ---- Phase 2: STORE. The connection is closed; nothing here is on a clock. ---------
  //
  // Messages read before a failure are still worth keeping — they are what lets a mailbox
  // that times out mid-read still come out of the sweep further ahead than it went in.
  for (const message of collected) {
    try {
      const envelope = message.envelope;
      const receivedAt = envelope?.date ?? new Date();
      // Belt and braces: the server filter is inclusive of the day, so re-check.
      if (receivedAt < since) continue;

      const parsed = await parseMessageSource(message.source);
      const headers = parsed.headers;

      // Envelope values win when the parse came back blank — a malformed body must not
      // cost us the sender or the subject, which is what triage runs on.
      const envelopeFrom = firstAddress(envelope?.from);
      const from = {
        email: parsed.fromEmail || envelopeFrom.email,
        name: parsed.fromName || envelopeFrom.name,
      };
      const subject = (parsed.subject || envelope?.subject || "").trim();

      // Matching and escalation keep reading FLATTENED PLAIN TEXT. Those rules were
      // tuned against it — feeding them markup would change what counts as an
      // escalation — so the HTML is carried alongside for display only.
      const plainSource = parsed.text.trim() ? parsed.text : parsed.html;
      const preview = toPreview(plainSource);
      const fullText = toFullText(plainSource);
      const bodyHtml = sanitizeEmailHtml(parsed.html);

      // --- match ---
      let match = NO_MATCH;
      const wos = extractWoNumbers(`${subject} ${preview}`);
      let woRow: { ticketId: string; caseId: string } | null = null;
      for (const wo of wos) {
        const found = await findRowByTicketId(wo);
        if (found) {
          woRow = { ticketId: found.ticketId, caseId: found.caseId };
          break;
        }
      }
      const senderRow = woRow ? null : await findRowByCustomerEmail(from.email);
      match = resolveMatch({ woInReport: woRow, senderRow });

      // Machine mail is never an escalation, so the auto flag is decided first.
      const autoFlag = isAutoGenerated(headers) || isNoReplySender(from.email);
      const escalation = detectEscalation({ subject, body: fullText, isAutoReply: autoFlag });

      const storedId = await insertInboundEmail({
        mailboxEmail: mailbox.email,
        regionCode: mailbox.regionCode,
        messageId: envelope?.messageId ?? `uid-${message.uid}@${mailbox.email}`,
        imapUid: Number(message.uid) || null,
        fromEmail: from.email,
        fromName: from.name,
        subject,
        bodyPreview: preview,
        bodyText: fullText,
        bodyHtml,
        hasAttachments: parsed.attachments.some((a) => !a.isInline),
        receivedAt: receivedAt.toISOString(),
        matchedTicketId: match.ticketId,
        matchedCaseId: match.caseId,
        matchMethod: match.method,
        matchConfidence: match.confidence,
        // Either flag bars the message from any future reply path.
        isAutoReply: autoFlag,
        escalationLevel: escalation.level,
        escalationReasons: escalation.reasons.join(" | "),
      });

      if (storedId) {
        result.stored += 1;
        if (match.method !== "NONE") result.matched += 1;

        // Files are secondary to the message: a mail whose attachments fail to store
        // is still readable and still triageable, so this must not abort the sweep.
        if (parsed.attachments.length > 0) {
          try {
            await insertInboundEmailAttachments(
              storedId,
              parsed.attachments.map((a) => ({
                contentId: a.contentId,
                filename: a.filename,
                mimeType: a.mimeType,
                sizeBytes: a.sizeBytes,
                isInline: a.isInline,
                content: a.content,
              })),
            );
          } catch (error) {
            console.error(
              `[mailWorker] attachments failed for ${mailbox.email} uid ${String(message.uid)}:`,
              error,
            );
          }
        }
      }
    } catch (error) {
      // One unreadable message must not cost the rest of the batch. It stays unstored, so
      // it is offered again next sweep; if it fails for ever it fails alone.
      console.error(
        `[mailWorker] message failed for ${mailbox.email} uid ${String(message.uid)}:`,
        error,
      );
    }
  }

  result.error = readError;
  await markMailboxPolled(mailbox.email, readError);
  return result;
}


/**
 * One sweep across every active mailbox.
 *
 * `onResult` fires as each mailbox finishes rather than at the end. A sweep draining a
 * backlog can run for many minutes, and reporting only on completion made a working sweep
 * indistinguishable from a hung one — the log stayed empty either way.
 */
export async function pollAllMailboxes(
  onResult?: (result: PollResult) => void,
): Promise<PollResult[]> {
  await registerConfiguredMailboxes();
  const mailboxes = await listActiveMailboxes();
  const results: PollResult[] = [];
  for (const mailbox of mailboxes) {
    const result = await pollMailbox(mailbox);
    results.push(result);
    onResult?.(result);
  }
  return results;
}
