import { ImapFlow } from "imapflow";
import {
  ensureMailbox,
  findRowByCustomerEmail,
  findRowByTicketId,
  insertInboundEmail,
  insertInboundEmailAttachments,
  listActiveMailboxes,
  markMailboxPolled,
  type RegionMailbox,
} from "../../repositories/inboundEmailRepository.js";
import { sanitizeEmailHtml } from "./htmlSanitizer.js";
import { parseMessageSource } from "./messageParser.js";
import {
  extractWoNumbers,
  isAutoGenerated,
  isNoReplySender,
  resolveMatch,
  toPreview,
  toFullText,
  NO_MATCH,
} from "./emailMatcher.js";
import { detectEscalation } from "./escalationDetector.js";
import { mailboxPassword } from "./mailboxCredentials.js";

/**
 * Customer email ingest — Stage 1: READ ONLY.
 *
 * Polls each registered region mailbox over IMAP, stores messages received AT OR AFTER that
 * mailbox's watermark, and records the best match to an open call.
 *
 * NOTHING IS EVER SENT. There is no SMTP code in this file on purpose: replies are a later
 * stage, switched on only once the matching has been watched in the UI.
 *
 * THE WATERMARK MATTERS. The live mailboxes hold years of history (3.5k-6.5k messages).
 * The IMAP SEARCH is bounded by `ingest_from`, stamped when the mailbox was registered, so
 * the back catalogue is never read and — when replies do arrive — no historical customer can
 * be answered years late.
 */

export interface MailboxConfig {
  regionCode: string;
  email: string;
}

/** Mailboxes declared in the environment. Chennai/Hosur appear once their keys are set. */
export function mailboxesFromEnv(): MailboxConfig[] {
  const map: Array<[string, string | undefined]> = [
    ["CHENNAI", process.env.MAIL_CHENNAI],
    ["SALEM", process.env.MAIL_SALEM],
    ["HOSUR", process.env.MAIL_HOSUR],
    ["VELLORE", process.env.MAIL_VELLORE],
    ["KANCHIPURAM", process.env.MAIL_KANCHIPURAM],
  ];
  return map
    .filter((entry): entry is [string, string] => Boolean(entry[1]?.trim()))
    .map(([regionCode, email]) => ({ regionCode, email: email.trim() }));
}

/** Register every configured mailbox, stamping each one's watermark on first sight. */
export async function registerConfiguredMailboxes(): Promise<RegionMailbox[]> {
  const registered: RegionMailbox[] = [];
  for (const config of mailboxesFromEnv()) {
    registered.push(await ensureMailbox(config));
  }
  return registered;
}

function firstAddress(
  value: { address?: string; name?: string }[] | undefined,
): { email: string; name: string } {
  const first = value?.[0];
  return {
    email: (first?.address ?? "").trim().toLowerCase(),
    name: (first?.name ?? "").trim(),
  };
}

export interface PollResult {
  mailbox: string;
  fetched: number;
  stored: number;
  matched: number;
  error: string;
}

/**
 * Poll one mailbox. Never throws: a mailbox that is down must not stop the others, and the
 * failure is recorded on the mailbox row for the UI.
 */
export async function pollMailbox(mailbox: RegionMailbox): Promise<PollResult> {
  const result: PollResult = {
    mailbox: mailbox.email,
    fetched: 0,
    stored: 0,
    matched: 0,
    error: "",
  };

  const host = process.env.MAIL_IMAP_HOST ?? "";
  const port = Number(process.env.MAIL_IMAP_PORT ?? 993);
  // This mailbox's own password when it has one — hosur's differs from the rest.
  const pass = mailboxPassword(mailbox.email);
  if (!host || !pass) {
    result.error = "MAIL_IMAP_HOST / MAIL_PASSWORD not configured";
    await markMailboxPolled(mailbox.email, result.error);
    return result;
  }

  const client = new ImapFlow({
    host,
    port,
    secure: true,
    auth: { user: mailbox.email, pass },
    logger: false,
    // The mailboxes are on shared hosting with a self-signed chain on some hostnames.
    tls: { rejectUnauthorized: false },
  });

  try {
    await client.connect();
    const lock = await client.getMailboxLock("INBOX");
    try {
      // THE GUARD: only mail at or after the watermark is even asked for.
      const since = new Date(mailbox.ingestFrom);
      const uids = await client.search({ since }, { uid: true });
      const list = Array.isArray(uids) ? uids : [];
      result.fetched = list.length;

      if (list.length > 0) {
        // The whole message, not just its text part: the reading pane shows the sender's
        // own HTML and their inline pictures, and both live in parts a "text" fetch skips.
        for await (const message of client.fetch(
          list,
          { uid: true, envelope: true, source: true },
          { uid: true },
        )) {
          const envelope = message.envelope;
          const receivedAt = envelope?.date ?? new Date();
          // Belt and braces: the server filter is inclusive of the day, so re-check.
          if (receivedAt < since) continue;

          const parsed = await parseMessageSource(message.source ?? Buffer.from([]));
          const headers = parsed.headers;

          // Envelope values win when the parse came back blank — a malformed body must not
          // cost us the sender or the subject, which is what triage runs on.
          const envelopeFrom = firstAddress(envelope?.from);
          const from = {
            email: parsed.fromEmail || envelopeFrom.email,
            name: parsed.fromName || envelopeFrom.name,
          };
          const subject = (parsed.subject || envelope?.subject || "").trim();

          // Matching and escalation keep reading FLATTENED PLAIN TEXT. Those rules were
          // tuned against it — feeding them markup would change what counts as an
          // escalation — so the HTML is carried alongside for display only.
          const plainSource = parsed.text.trim() ? parsed.text : parsed.html;
          const preview = toPreview(plainSource);
          const fullText = toFullText(plainSource);
          const bodyHtml = sanitizeEmailHtml(parsed.html);

          // --- match ---
          let match = NO_MATCH;
          const wos = extractWoNumbers(`${subject} ${preview}`);
          let woRow: { ticketId: string; caseId: string } | null = null;
          for (const wo of wos) {
            const found = await findRowByTicketId(wo);
            if (found) {
              woRow = { ticketId: found.ticketId, caseId: found.caseId };
              break;
            }
          }
          const senderRow = woRow ? null : await findRowByCustomerEmail(from.email);
          match = resolveMatch({ woInReport: woRow, senderRow });

          // Machine mail is never an escalation, so the auto flag is decided first.
          const autoFlag = isAutoGenerated(headers) || isNoReplySender(from.email);
          const escalation = detectEscalation({ subject, body: fullText, isAutoReply: autoFlag });

          const storedId = await insertInboundEmail({
            mailboxEmail: mailbox.email,
            regionCode: mailbox.regionCode,
            messageId: envelope?.messageId ?? `uid-${message.uid}@${mailbox.email}`,
            imapUid: Number(message.uid) || null,
            fromEmail: from.email,
            fromName: from.name,
            subject,
            bodyPreview: preview,
            bodyText: fullText,
            bodyHtml,
            hasAttachments: parsed.attachments.some((a) => !a.isInline),
            receivedAt: receivedAt.toISOString(),
            matchedTicketId: match.ticketId,
            matchedCaseId: match.caseId,
            matchMethod: match.method,
            matchConfidence: match.confidence,
            // Either flag bars the message from any future reply path.
            isAutoReply: autoFlag,
            escalationLevel: escalation.level,
            escalationReasons: escalation.reasons.join(" | "),
          });

          if (storedId) {
            result.stored += 1;
            if (match.method !== "NONE") result.matched += 1;

            // Files are secondary to the message: a mail whose attachments fail to store
            // is still readable and still triageable, so this must not abort the sweep.
            if (parsed.attachments.length > 0) {
              try {
                await insertInboundEmailAttachments(
                  storedId,
                  parsed.attachments.map((a) => ({
                    contentId: a.contentId,
                    filename: a.filename,
                    mimeType: a.mimeType,
                    sizeBytes: a.sizeBytes,
                    isInline: a.isInline,
                    content: a.content,
                  })),
                );
              } catch (error) {
                console.error(
                  `[mailWorker] attachments failed for ${mailbox.email} uid ${String(message.uid)}:`,
                  error,
                );
              }
            }
          }
        }
      }
    } finally {
      lock.release();
    }
    await markMailboxPolled(mailbox.email, "");
  } catch (error) {
    result.error = error instanceof Error ? error.message : String(error);
    await markMailboxPolled(mailbox.email, result.error);
  } finally {
    try {
      await client.logout();
    } catch {
      /* already closed */
    }
  }

  return result;
}

/** One sweep across every active mailbox. */
export async function pollAllMailboxes(): Promise<PollResult[]> {
  await registerConfiguredMailboxes();
  const mailboxes = await listActiveMailboxes();
  const results: PollResult[] = [];
  for (const mailbox of mailboxes) {
    results.push(await pollMailbox(mailbox));
  }
  return results;
}
