import { Router } from "express";
import { adminRouter } from "./adminRoutes.js";
import { authRouter } from "./authRoutes.js";
import { healthRouter } from "./healthRoutes.js";
import { historyRouter } from "./historyRoutes.js";
import { matchRouter } from "./matchRoutes.js";
import { meRouter } from "./meRoutes.js";
import { recordLayoutRouter } from "./recordLayoutRoutes.js";
import { reportRouter } from "./reportRoutes.js";
import { reportRowRouter } from "./reportRowRoutes.js";
import { uploadRouter } from "./uploadRoutes.js";
import { closureDateRouter } from "./closureDateRoutes.js";
import { flexRawDataRouter } from "./flexRawDataRoutes.js";
import { regionEodRouter } from "./eodRoutes.js";
import { customerFeedbackRouter } from "./customerFeedbackRoutes.js";
import { partsCatalogRouter } from "./partsCatalogRoutes.js";
import { quotationRouter } from "./quotationRoutes.js";
import { specialAccessSessionRouter } from "./specialAccessSessionRoutes.js";
import { warrantyRouter } from "./warrantyRoutes.js";

export const apiRouter = Router();

apiRouter.use("/auth", authRouter);
apiRouter.use("/health", healthRouter);
apiRouter.use("/matches", matchRouter);
apiRouter.use("/reports", reportRouter);
apiRouter.use("/report-rows", reportRowRouter);
apiRouter.use("/uploads", uploadRouter);
apiRouter.use("/closure-dates", closureDateRouter);
apiRouter.use("/flex-raw", flexRawDataRouter);
apiRouter.use("/regions", regionEodRouter);
apiRouter.use("/customer-feedback", customerFeedbackRouter);
apiRouter.use("/parts-catalog", partsCatalogRouter);
apiRouter.use("/quotations", quotationRouter);
apiRouter.use("/report-history", historyRouter);
apiRouter.use("/admin", adminRouter);
apiRouter.use("/me", meRouter);
apiRouter.use("/record-layout", recordLayoutRouter);
apiRouter.use("/special-access", specialAccessSessionRouter);
apiRouter.use("/warranty", warrantyRouter);
